create  table  item
(
 id  INT(11) NULL DEFAULT NULL,
 name VARCHAR(50) NULL DEFAULT NULL,
 category VARCHAR(50) NULL DEFAULT NULL

);

INSERT INTO ITEM(ID, NAME, CATEGORY)
VALUES(1, 'Apple', 'MobIle');
INSERT INTO ITEM(ID, NAME, CATEGORY)
VALUES(2, 'LG', 'TELEVISION');
INSERT INTO ITEM(ID, NAME, CATEGORY)
VALUES(3, 'HP', 'LAPTOP');
INSERT INTO ITEM(ID, NAME, CATEGORY)
VALUES(4, 'MOTOR', 'V-GUARD');


